version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: glpi-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpipassword
    volumes:
      - db_data:/var/lib/mysql

  glpi:
    image: diouxx/glpi
    container_name: glpi
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"  # ⚠️ Attention : on évite 8080 car Zabbix l'utilise déjà
    environment:
      TIMEZONE: Europe/Paris
    volumes:
      - glpi_data:/var/www/html

volumes:
  db_data:
  glpi_data:
